Name: Enemy1
Species: 7
Parts:
- Name: SK_HUMN_BASE_02_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_HUMN_BASE_01_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_23AFAC_HU01
  PartType: AttachmentFace
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_01_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_SCFI_CIVL_10_22AHED_HU01
  PartType: AttachmentHead
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_30ASHR_HU01
  PartType: AttachmentShoulderRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_29ASHL_HU01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_FANT_KNGT_17_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_FANT_KNGT_17_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_SCFI_CIVL_09_25AHPF_HU01
  PartType: AttachmentHipsFront
  PartVersion: 1
ColorSet:
  Species: 7
  Name: Custom
  SourceColorPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 2
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 3
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 4
  MainColor: 635D43
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 5
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 6
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 7
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 8
  MainColor: 4B473B
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 9
  MainColor: 4B473B
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 10
  MainColor: 4B473B
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 11
  MainColor: 4B473B
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 12
  MainColor: 4B473B
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 13
  MainColor: 4B473B
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 14
  MainColor: 655E40
  Metallic: 818181
  Smoothness: 818181
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 15
  MainColor: EA9999
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 16
  MainColor: E5D8AF
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 17
  MainColor: CBBE93
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 18
  MainColor: EA9999
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 19
  MainColor: EA9999
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 20
  MainColor: AC6041
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 21
  MainColor: AC6041
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 22
  MainColor: 8D4E34
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 23
  MainColor: 8D4E34
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 24
  MainColor: 1E1C1C
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 25
  MainColor: 1E1C1C
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 26
  MainColor: 151515
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 27
  MainColor: 151515
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 30
  MainColor: 212126
  Metallic: 747474
  Smoothness: 747474
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 31
  MainColor: 212126
  Metallic: 747474
  Smoothness: 747474
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 32
  MainColor: 212126
  Metallic: 747474
  Smoothness: 747474
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 33
  MainColor: 212126
  Metallic: 747474
  Smoothness: 747474
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 34
  MainColor: 4B473B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 35
  MainColor: 212126
  Metallic: 747474
  Smoothness: 747474
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 36
  MainColor: 212126
  Metallic: 747474
  Smoothness: 747474
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 37
  MainColor: 4B473B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 38
  MainColor: B35149
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 39
  MainColor: 944842
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 40
  MainColor: AFA382
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 41
  MainColor: 94896F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 42
  MainColor: 998B79
- ColorProperty: 43
  MainColor: 535660
- ColorProperty: 44
  MainColor: 514C46
- ColorProperty: 45
  MainColor: 7D6652
- ColorProperty: 46
  MainColor: 6A5C4D
- ColorProperty: 47
  MainColor: 76554E
- ColorProperty: 48
  MainColor: 918473
- ColorProperty: 49
  MainColor: 504B45
- ColorProperty: 50
  MainColor: 7D7973
- ColorProperty: 51
  MainColor: 6A6660
- ColorProperty: 52
  MainColor: 7B5650
- ColorProperty: 53
  MainColor: 998B79
- ColorProperty: 54
  MainColor: 514C46
- ColorProperty: 55
  MainColor: 898580
- ColorProperty: 56
  MainColor: 76726C
- ColorProperty: 57
  MainColor: 7B5650
- ColorProperty: 58
  MainColor: 998B79
- ColorProperty: 59
  MainColor: 514C46
- ColorProperty: 60
  MainColor: 898580
- ColorProperty: 61
  MainColor: 76726C
- ColorProperty: 62
  MainColor: 76554E
- ColorProperty: 63
  MainColor: 918473
- ColorProperty: 64
  MainColor: 504B45
- ColorProperty: 65
  MainColor: 7D7973
- ColorProperty: 66
  MainColor: 6A6660
- ColorProperty: 67
  MainColor: 69584A
- ColorProperty: 68
  MainColor: 47474E
- ColorProperty: 69
  MainColor: 814A45
- ColorProperty: 70
  MainColor: 998B79
- ColorProperty: 71
  MainColor: 575655
- ColorProperty: 72
  MainColor: 69584A
- ColorProperty: 73
  MainColor: 535660
- ColorProperty: 74
  MainColor: 514C46
- ColorProperty: 75
  MainColor: 998B79
- ColorProperty: 76
  MainColor: 575655
- ColorProperty: 77
  MainColor: 69584A
- ColorProperty: 78
  MainColor: 535660
- ColorProperty: 79
  MainColor: 514C46
- ColorProperty: 80
  MainColor: 998B79
- ColorProperty: 81
  MainColor: 575655
- ColorProperty: 82
  MainColor: 69584A
- ColorProperty: 83
  MainColor: 535660
- ColorProperty: 84
  MainColor: 514C46
- ColorProperty: 85
  MainColor: 998B79
- ColorProperty: 86
  MainColor: 575655
- ColorProperty: 87
  MainColor: 69584A
- ColorProperty: 88
  MainColor: 535660
- ColorProperty: 89
  MainColor: 514C46
- ColorProperty: 90
  MainColor: 998B79
- ColorProperty: 91
  MainColor: 575655
- ColorProperty: 92
  MainColor: 7A593E
- ColorProperty: 93
  MainColor: 7A593E
- ColorProperty: 94
  MainColor: B7B7B7
- ColorProperty: 95
  MainColor: 4C3A2D
- ColorProperty: 96
  MainColor: 282E3C
- ColorProperty: 97
  MainColor: 222221
- ColorProperty: 98
  MainColor: 72695E
- ColorProperty: 99
  MainColor: 2A2D31
- ColorProperty: 100
  MainColor: 4C3A2D
- ColorProperty: 101
  MainColor: 2D364C
- ColorProperty: 102
  MainColor: 2A2928
- ColorProperty: 103
  MainColor: 8D806F
- ColorProperty: 104
  MainColor: 32363D
- ColorProperty: 105
  MainColor: 4C3A2D
- ColorProperty: 106
  MainColor: 2D364C
- ColorProperty: 107
  MainColor: 2A2928
- ColorProperty: 108
  MainColor: 8D806F
- ColorProperty: 109
  MainColor: 32363D
- ColorProperty: 110
  MainColor: 7B5650
- ColorProperty: 111
  MainColor: 998B79
- ColorProperty: 112
  MainColor: 514C46
- ColorProperty: 113
  MainColor: 898580
- ColorProperty: 114
  MainColor: 76726C
- ColorProperty: 115
  MainColor: 76554E
- ColorProperty: 116
  MainColor: 918473
- ColorProperty: 117
  MainColor: 504B45
- ColorProperty: 118
  MainColor: 7D7973
- ColorProperty: 119
  MainColor: 6A6660
- ColorProperty: 120
  MainColor: 7B5650
- ColorProperty: 121
  MainColor: 998B79
- ColorProperty: 122
  MainColor: 514C46
- ColorProperty: 123
  MainColor: 898580
- ColorProperty: 124
  MainColor: 76726C
- ColorProperty: 125
  MainColor: 76554E
- ColorProperty: 126
  MainColor: 918473
- ColorProperty: 127
  MainColor: 504B45
- ColorProperty: 128
  MainColor: 7D7973
- ColorProperty: 129
  MainColor: 6A6660
- ColorProperty: 130
  MainColor: 7B5650
- ColorProperty: 131
  MainColor: 998B79
- ColorProperty: 132
  MainColor: 514C46
- ColorProperty: 133
  MainColor: 898580
- ColorProperty: 134
  MainColor: 76726C
- ColorProperty: 135
  MainColor: 76554E
- ColorProperty: 136
  MainColor: 918473
- ColorProperty: 137
  MainColor: 504B45
- ColorProperty: 138
  MainColor: 7D7973
- ColorProperty: 139
  MainColor: 6A6660
- ColorProperty: 140
  MainColor: 7B5650
- ColorProperty: 141
  MainColor: 998B79
- ColorProperty: 142
  MainColor: 514C46
- ColorProperty: 143
  MainColor: 898580
- ColorProperty: 144
  MainColor: 76726C
- ColorProperty: 145
  MainColor: 76554E
- ColorProperty: 146
  MainColor: 918473
- ColorProperty: 147
  MainColor: 504B45
- ColorProperty: 148
  MainColor: 7D7973
- ColorProperty: 149
  MainColor: 6A6660
- ColorProperty: 150
  MainColor: 7B5650
- ColorProperty: 151
  MainColor: 998B79
- ColorProperty: 152
  MainColor: 514C46
- ColorProperty: 153
  MainColor: 898580
- ColorProperty: 154
  MainColor: 76726C
- ColorProperty: 155
  MainColor: 76554E
- ColorProperty: 156
  MainColor: 918473
- ColorProperty: 157
  MainColor: 504B45
- ColorProperty: 158
  MainColor: 7D7973
- ColorProperty: 159
  MainColor: 6A6660
- ColorProperty: 160
  MainColor: 7C7872
- ColorProperty: 161
  MainColor: 65605A
- ColorProperty: 162
  MainColor: 55524A
- ColorProperty: 163
  MainColor: 3D3934
- ColorProperty: 164
  MainColor: 8C8194
- ColorProperty: 165
  MainColor: 796C8A
- ColorProperty: 166
  MainColor: B2A075
- ColorProperty: 167
  MainColor: B29A5C
- ColorProperty: 168
  MainColor: FF9C07
- ColorProperty: 169
  MainColor: FF9C07
- ColorProperty: 170
  MainColor: 33ADA8
- ColorProperty: 171
  MainColor: 33AD77
- ColorProperty: 172
  MainColor: 9A9FA2
- ColorProperty: 173
  MainColor: 949AA2
- ColorProperty: 174
  MainColor: 8D997D
- ColorProperty: 175
  MainColor: 849471
- ColorProperty: 176
  MainColor: 3C3B3A
- ColorProperty: 177
  MainColor: 373635
- ColorProperty: 178
  MainColor: 8E8984
- ColorProperty: 179
  MainColor: 8E8984
- ColorProperty: 180
  MainColor: A29883
- ColorProperty: 181
  MainColor: 9A8F77
- ColorProperty: 182
  MainColor: 8E806F
- ColorProperty: 183
  MainColor: 897967
- ColorProperty: 184
  MainColor: 7D6652
- ColorProperty: 185
  MainColor: 826D5A
- ColorProperty: 186
  MainColor: 716152
- ColorProperty: 187
  MainColor: 685647
- ColorProperty: 188
  MainColor: 998B79
- ColorProperty: 189
  MainColor: 998B79
- ColorProperty: 190
  MainColor: 998B79
- ColorProperty: 191
  MainColor: 998B79
- ColorProperty: 192
  MainColor: AAA5A0
- ColorProperty: 193
  MainColor: AAA5A0
- ColorProperty: 194
  MainColor: 7D6652
- ColorProperty: 195
  MainColor: 8D7057
- ColorProperty: 196
  MainColor: 6D8080
- ColorProperty: 197
  MainColor: 697D9E
- ColorProperty: 198
  MainColor: FFFFFF
- ColorProperty: 199
  MainColor: FFFFFF
- ColorProperty: 200
  MainColor: FFFFFF
- ColorProperty: 201
  MainColor: FFFFFF
- ColorProperty: 202
  MainColor: FFFFFF
- ColorProperty: 203
  MainColor: FFFFFF
- ColorProperty: 204
  MainColor: FFFFFF
- ColorProperty: 205
  MainColor: FFFFFF
- ColorProperty: 206
  MainColor: FFFFFF
- ColorProperty: 207
  MainColor: FFFFFF
- ColorProperty: 208
  MainColor: FFFFFF
- ColorProperty: 209
  MainColor: FFFFFF
BlendShapes:
  BodyTypeValue: -100
  BodySizeValue: 100
  MuscleValue: 100
